name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "17 7 * * *"

permissions:
  contents: read

jobs:
  compliance-audit:
    name: "Compliance Audit"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # Run the auth action first, to fail fast if connection with Google Cloud
      # has not been configured correctly.
      #
      # This avoids wasting GitHub Action minutes on preceding steps in case of an
      # authentication failure. The other steps in the job are unlikely to fail.
      - uses: "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093" # v3.0.0
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - run: nix run .#nix-develop .#workflow
      - run: pnpm install

      - run: ./node_modules/.bin/tsc --build
      - run: node dist/bin/turma.js
